apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730212195611:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LZIHD81F2A97
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::730212195611:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-29T00:01:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1214"
  uid: 24a7b483-b778-4858-9e20-702628445a4c
